LogInLogOut/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LogInLogOut.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        [Authorize]
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

LogInLogOut/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LogInLogOut.Models;
using System.Web.Security;

namespace LogInLogOut.Controllers
{
    public class LogInAdminController : Controller
    {
     
        //LogIn
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //LogIn POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Authorize(LogInLogOut.Models.AdminLogin userModel)
        {
            using (BloodDonorDBEntities db = new BloodDonorDBEntities())
            {
                var userDetails = db.AdminUsers.Where(x => x.AdminEmail == userModel.AdminEmail && x.AdminPassword == userModel.AdminPassword).FirstOrDefault();
                if (userDetails==null)
                {
                    userModel.LoginErrorMessage = "Wrong username or paswword";
                    return View("Index", userModel);
                }
                else
                {
                    Session["admin_id"] = userDetails.admin_id;
                    Session["AdminEmail"] = userDetails.AdminEmail;
                    return RedirectToAction("Dashboard", "Home");
                }
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            int adminID = (int)Session["admin_id"];
            Session.Abandon();
            FormsAuthentication.SignOut();
            return RedirectToAction("Authorize", "LogIn");
        }
    }
}

LogInLogOut/Views/Home/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    if (Session["admin_id"] == null)
    {
        Response.Redirect("~/LogInAdmin/Login");
    }
}

<h2>Dashboard</h2>

    <h3>Username: @Session["AdminEmail"].ToString()</h3>
    <a href="@Url.Action("Logout", "LogInAdmin")">Logout</a>

Welcome @HttpContext.Current.User.Identity.Name

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Logout", "RegisterUser", FormMethod.Post, new { id = "logoutForm" }))
    {
        <a href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
    }
}